### ISSUE TITLE
Authn MFE is broken in nightly

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor-mfe#122] opened 2023-04-26 14:31 UTC
## Steps to reproduce

* `tutor local start`
* Go to http://local.overhang.io
* This should redirect you to http://apps.local.overhang.io/authn/login
* Expected: The login page
* Actual: `An unexpected error occurred. Please click the button below to refresh the page.`
* Refreshing the page leads the same error

## Notes

* I've confirmed that `tutor local launch` does not fix the issue.
* @bmtcril confirms that that deleting all data and re-launching does not fix the issue.
* @bmtcril was able to disable the mfe plugin, use the legacy login page, re-enable the mfe plugin, and then use the Learning MFE. This implies that the issue is not specific to MFEs or to authentication, but is an issue at intersection of the two and/or the an bug in the Authn MFE iteslf.
* `tutor dev` also fails.

**Comment by brian-smith-tcril** [comment] 2023-04-26 16:06
tried
```
rm -rf node_modules/
nvm use 16
npm install
npm start
```

still seems to be working

**Comment by ghassanmas** [comment] 2023-04-26 16:12
Can you try running it using dynamic config enabled I think this one main difference between devstack and tutor. You would need to see ENV variable to the minimum needed and then serve the other by setting dynamic config apo

**Comment by ghassanmas** [comment] 2023-04-26 17:10
[update] I don't know if that's help. but I tried to run/build the authn mfe `master` while using tutor `palm` (using `palm.master` instead of `master`  and it worked with no problem. In any case this probably mean the issue irreleant to frontend-platform version

**Comment by ghassanmas** [comment] 2023-04-26 18:36
I was able to reproduce this issue, and to resolved in hacky way where I cloned maste of authn and then mounted the dist to mfe the container. When I noticed is that the mfe image doesn't have `nightly` suffix, as opposite the openedx image. So I guess it was using the olive image for nightly. 
```bash
(edx-env) ➜  tutor-nightly tutor config printvalue DOCKER_IMAGE_OPENEDX
docker.io/overhangio/openedx:15.3.4-nightly
(edx-env) ➜  tutor-nightly tutor config printvalue MFE_DOCKER_IMAGE
docker.io/overhangio/openedx-mfe:15.0.5
```
So may be running `tutor images build mfe` suppose to resolve?.... it's building now for me, so I can update when it's done

**Comment by arbrandes** [comment] 2023-05-02 17:50
I can take a look over the next couple of days, yes!

**Comment by brian-smith-tcril** [comment] 2023-05-11 15:56
I've been doing a bit of digging into this, when running `tutor dev start` I noticed
```
  Your models in app(s): 'third_party_auth' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

when breaking into the errors using a browser debugger I found issues with how we were setting `thirdPartyAuthContext`, it seems that has changed recently https://github.com/openedx/frontend-app-authn/blame/master/src/common-components/data/service.js#L23

I'm still looking into this, I'll make sure to share updates as I discover more.

**Comment by brian-smith-tcril** [comment] 2023-05-11 15:59
Update: running `tutor images build authn-dev` fixed this for me. 

```
Successfully built b058f87eab3d
Successfully tagged overhangio/openedx-authn-dev:15.0.5
```

compared to the current image on dockerhub (`15.0.2` - 5 months ago) https://hub.docker.com/r/overhangio/authn-dev/tags

**Comment by brian-smith-tcril** [comment] 2023-05-11 17:51
@regisb do you have any insights into this? It seems the required `frontend-app-authn` change was this https://github.com/openedx/frontend-app-authn/commit/62e8f75b96994d9a281f6a7a217ae7632665d9af

I think my main concern is that running `tutor dev launch` on nightly doesn't guarantee the latest MFE code is pulled.

**Comment by regisb** [comment] 2023-05-16 11:40
We do not push nightly images to dockerhub for MFEs, so users need to re-build them locally. @brian-smith-tcril do I understand correctly that re-building fixes the issue for you?

**Comment by brian-smith-tcril** [comment] 2023-05-16 17:53
> do I understand correctly that re-building fixes the issue for you?

Yes

> running tutor images build authn-dev fixed this for me.

I didn't test `tutor local` but I assume `tutor images build mfe` would work for that

**Comment by bmtcril** [comment] 2023-05-16 18:03
It worked on `tutor local` for myself and some other folks. 

Is there any indication of when someone would need to rebuild the MFE image locally, or is it just "something broke, try rebuilding the image"? What causes the MFE image to be pushed to dockerhub now?

**Comment by regisb** [comment] 2023-05-17 08:38
The docs state that nightly images can be pulled from dockerhub: https://docs.tutor.overhang.io/tutorials/nightly.html#upgrading-to-the-latest-version-of-open-edx

But this is factually incorrect. Only the "openedx" image is pushed to dockerhub: https://hub.docker.com/r/overhangio/openedx/tags?page=1&name=nightly CI does not push nightly images for plugins.

To offer a better user experience in nightly, we should also push nightly images for plugins. But it is unlikely that non-official images will go to the trouble of setting up a CI to push nightly images (with a different tag) to their registries.

So, I'm not sure what we should be doing here. Should we just rebuild all images automatically during `launch` on the nightly branch? Of course, at the very least we should fix the docs.

**Comment by arbrandes** [comment] 2023-05-17 16:45
> Should we just rebuild all images automatically during `launch` on the nightly branch?

If the images don't already exist locally, I think this is perfectly reasonable.

**Comment by regisb** [comment] 2023-10-02 12:55
I think we really don't want to re-build the mfe nightly images every day, so I'll close this. Feel free to reopen if you think differently.

**Closed by regisb** 2023-10-02 12:55 UTC
Labels: bug
